### ISSUE TITLE
Mention attributes while searching

### ISSUE THREAD

**Issue by abdullahtariq1171** [mechanicles/ruby_simple_search#3]
Suppose you want to search on different attributes depending on scenario.

```
class Post < ActiveActiveRecord::Base
  include RubySimpleSearch

  simple_search_attributes :title, :description
end
```
`Post.simple_search('tuto', :pattern => :beginning)`

In above case it will always search in `:title` and `:description` but what if i only want to search in one (or more) specified attributes?

Something like this?
`Post.simple_search('tuto', :pattern => :beginning,  :attributes => :description)`

This feature will provide more flexibility.

**Comment by mechanicles** [comment]
@abdullahtariq1171 Thanks! I liked the idea. I will work on it soon.

**Comment by abdullahtariq1171** [comment]
I have implemented this feature [here](https://github.com/abdullahtariq1171/ruby_simple_search/commit/447c2b44d641bd9eabd9d4970e905762445b3b04).
`development` branch is note updated, should I create pull request for `master` branch?
